"""
Base de conocimiento estático del módulo de Tarot.
Datos puros — sin imports externos.
Sistemas: RWS (Rider-Waite-Smith), Marsella, Thoth.
"""
from __future__ import annotations

# ─── Arcanos Mayores ─────────────────────────────────────────────────────────
# Clave = nombre RWS español canónico

ARCANOS_MAYORES: dict[str, dict] = {
    "El Loco": {
        "numero": 0,
        "nombre_rws": "El Loco",
        "nombre_marsella": "Le Mat",
        "nombre_thoth": "The Fool",
        "elemento": "aire",
        "planeta": "urano",
        "signo": "",
        "letra_hebrea": "Aleph",
        "palabras_clave": ["libertad", "inicio", "espontaneidad", "aventura", "confianza"],
        "sombra": ["irresponsabilidad", "ingenuidad peligrosa", "evasión", "imprudencia"],
        "pregunta_terapeutica": "¿En qué área de tu vida necesitas dar un salto de fe sin garantías?",
        "arquetipo": "El Niño Eterno / Puer Aeternus",
        "afirmacion": "Confío en el viaje de mi vida y doy el siguiente paso con alegría.",
    },
    "El Mago": {
        "numero": 1,
        "nombre_rws": "El Mago",
        "nombre_marsella": "Le Bateleur",
        "nombre_thoth": "The Magus",
        "elemento": "aire",
        "planeta": "mercurio",
        "signo": "",
        "letra_hebrea": "Beth",
        "palabras_clave": ["voluntad", "manifestación", "habilidad", "concentración", "poder personal"],
        "sombra": ["manipulación", "engaño", "uso del poder para dañar", "dispersión"],
        "pregunta_terapeutica": "¿Qué herramientas tienes a tu disposición que aún no estás usando plenamente?",
        "arquetipo": "El Mago / Hermes",
        "afirmacion": "Tengo todo lo que necesito para crear la vida que deseo.",
    },
    "La Sacerdotisa": {
        "numero": 2,
        "nombre_rws": "La Sacerdotisa",
        "nombre_marsella": "La Papesse",
        "nombre_thoth": "The Priestess",
        "elemento": "agua",
        "planeta": "luna",
        "signo": "",
        "letra_hebrea": "Gimel",
        "palabras_clave": ["intuición", "misterio", "sabiduría interior", "silencio", "receptividad"],
        "sombra": ["secretismo excesivo", "desconexión emocional", "pasividad paralizante", "frialdad"],
        "pregunta_terapeutica": "¿Qué sabe tu intuición que tu mente racional aún no acepta?",
        "arquetipo": "La Gran Diosa / Anima",
        "afirmacion": "Confío en mi sabiduría interior y en los mensajes de mi intuición.",
    },
    "La Emperatriz": {
        "numero": 3,
        "nombre_rws": "La Emperatriz",
        "nombre_marsella": "L'Impératrice",
        "nombre_thoth": "The Empress",
        "elemento": "tierra",
        "planeta": "venus",
        "signo": "",
        "letra_hebrea": "Daleth",
        "palabras_clave": ["abundancia", "fertilidad", "naturaleza", "creatividad", "amor materno"],
        "sombra": ["sobreprotección", "dependencia material", "posesividad", "estancamiento"],
        "pregunta_terapeutica": "¿Cómo te nutres a ti mismo/a y qué necesitas para florecer?",
        "arquetipo": "La Gran Madre / Deméter",
        "afirmacion": "Me permito recibir abundancia y nutro lo que amo con generosidad.",
    },
    "El Emperador": {
        "numero": 4,
        "nombre_rws": "El Emperador",
        "nombre_marsella": "L'Empereur",
        "nombre_thoth": "The Emperor",
        "elemento": "fuego",
        "planeta": "marte",
        "signo": "aries",
        "letra_hebrea": "He",
        "palabras_clave": ["autoridad", "estructura", "protección", "orden", "paternidad"],
        "sombra": ["autoritarismo", "rigidez", "control excesivo", "tiranía", "inflexibilidad"],
        "pregunta_terapeutica": "¿Dónde necesitas establecer límites y estructura en tu vida?",
        "arquetipo": "El Padre / Zeus",
        "afirmacion": "Establezco estructuras que me sostienen y protejo lo que valoro.",
    },
    "El Sumo Sacerdote": {
        "numero": 5,
        "nombre_rws": "El Sumo Sacerdote",
        "nombre_marsella": "Le Pape",
        "nombre_thoth": "The Hierophant",
        "elemento": "tierra",
        "planeta": "jupiter",
        "signo": "tauro",
        "letra_hebrea": "Vav",
        "palabras_clave": ["tradición", "enseñanza", "creencias", "comunidad", "guía espiritual"],
        "sombra": ["dogmatismo", "conformismo", "moralismo rígido", "hipocresía", "control religioso"],
        "pregunta_terapeutica": "¿Qué creencias heredadas te limitan y cuáles genuinamente te sostienen?",
        "arquetipo": "El Maestro / El Guardián de la Tradición",
        "afirmacion": "Honro la sabiduría que me antecede y sigo mi propio camino espiritual.",
    },
    "Los Amantes": {
        "numero": 6,
        "nombre_rws": "Los Amantes",
        "nombre_marsella": "L'Amoureux",
        "nombre_thoth": "The Lovers",
        "elemento": "aire",
        "planeta": "mercurio",
        "signo": "geminis",
        "letra_hebrea": "Zayin",
        "palabras_clave": ["elección", "amor", "valores", "integración", "unión consciente"],
        "sombra": ["indecisión", "conflicto de valores", "infidelidad", "dependencia emocional"],
        "pregunta_terapeutica": "¿Qué elección estás evitando tomar porque temes perder algo?",
        "arquetipo": "Eros y Psique / La Unión de Opuestos",
        "afirmacion": "Elijo desde mi corazón y honro mis valores más profundos.",
    },
    "El Carro": {
        "numero": 7,
        "nombre_rws": "El Carro",
        "nombre_marsella": "Le Chariot",
        "nombre_thoth": "The Chariot",
        "elemento": "agua",
        "planeta": "luna",
        "signo": "cancer",
        "letra_hebrea": "Cheth",
        "palabras_clave": ["victoria", "control", "determinación", "voluntad", "movimiento"],
        "sombra": ["agresividad", "control excesivo", "arrogancia", "atropellar a otros"],
        "pregunta_terapeutica": "¿Qué fuerzas internas contrarias necesitas integrar para avanzar?",
        "arquetipo": "El Guerrero / El Héroe",
        "afirmacion": "Dirijo mis energías con determinación hacia mis metas más elevadas.",
    },
    "La Fuerza": {
        "numero": 8,
        "nombre_rws": "La Fuerza",
        "nombre_marsella": "La Force",
        "nombre_thoth": "Lust",
        "elemento": "fuego",
        "planeta": "sol",
        "signo": "leo",
        "letra_hebrea": "Teth",
        "palabras_clave": ["valentía", "compasión", "fuerza interior", "dominio suave", "paciencia"],
        "sombra": ["debilidad disfrazada", "represión", "cobardía", "crueldad", "impulsividad"],
        "pregunta_terapeutica": "¿Qué aspecto de ti mismo/a necesitas abrazar con compasión en lugar de reprimir?",
        "arquetipo": "La Heroína / Perséfone domando a Plutón",
        "afirmacion": "Mi fuerza verdadera emerge desde el amor y la compasión, no desde el miedo.",
    },
    "El Ermitaño": {
        "numero": 9,
        "nombre_rws": "El Ermitaño",
        "nombre_marsella": "L'Hermite",
        "nombre_thoth": "The Hermit",
        "elemento": "tierra",
        "planeta": "mercurio",
        "signo": "virgo",
        "letra_hebrea": "Yod",
        "palabras_clave": ["introspección", "guía interior", "soledad fértil", "sabiduría", "búsqueda"],
        "sombra": ["aislamiento", "soledad no elegida", "amargura", "rechazo al mundo"],
        "pregunta_terapeutica": "¿Qué encontrarías si te tomaras tiempo de verdadera soledad y silencio interior?",
        "arquetipo": "El Sabio / Kronos",
        "afirmacion": "En el silencio encuentro mi guía más verdadera y mi luz interior.",
    },
    "La Rueda de la Fortuna": {
        "numero": 10,
        "nombre_rws": "La Rueda de la Fortuna",
        "nombre_marsella": "La Roue de Fortune",
        "nombre_thoth": "Fortune",
        "elemento": "fuego",
        "planeta": "jupiter",
        "signo": "",
        "letra_hebrea": "Kaph",
        "palabras_clave": ["ciclos", "destino", "cambio", "oportunidad", "karma"],
        "sombra": ["resistencia al cambio", "víctima del destino", "irresponsabilidad kármica"],
        "pregunta_terapeutica": "¿Qué ciclo de tu vida está llegando a su fin y qué nuevo ciclo quieres iniciar?",
        "arquetipo": "La Rueda del Karma / Las Moiras",
        "afirmacion": "Fluyo con los ciclos de la vida y reconozco las oportunidades en cada cambio.",
    },
    "La Justicia": {
        "numero": 11,
        "nombre_rws": "La Justicia",
        "nombre_marsella": "La Justice",
        "nombre_thoth": "Adjustment",
        "elemento": "aire",
        "planeta": "venus",
        "signo": "libra",
        "letra_hebrea": "Lamed",
        "palabras_clave": ["equilibrio", "verdad", "responsabilidad", "causa-efecto", "claridad"],
        "sombra": ["juicio excesivo", "rigidez moral", "evitar responsabilidades", "parcialidad"],
        "pregunta_terapeutica": "¿Qué decisión has estado postergando porque requiere asumir una responsabilidad difícil?",
        "arquetipo": "Temis / La Balanza de Ma'at",
        "afirmacion": "Actúo con integridad y acepto las consecuencias de mis elecciones.",
    },
    "El Colgado": {
        "numero": 12,
        "nombre_rws": "El Colgado",
        "nombre_marsella": "Le Pendu",
        "nombre_thoth": "The Hanged Man",
        "elemento": "agua",
        "planeta": "neptuno",
        "signo": "",
        "letra_hebrea": "Mem",
        "palabras_clave": ["pausa", "entrega", "perspectiva nueva", "sacrificio", "rendición"],
        "sombra": ["martirio", "parálisis", "victimismo", "autosabotaje", "indecisión crónica"],
        "pregunta_terapeutica": "¿Qué necesitas soltar para ver tu situación desde un ángulo completamente diferente?",
        "arquetipo": "Odín colgado del Yggdrasil / El Iniciado",
        "afirmacion": "Me permito pausar y rendirme al proceso. En la entrega encuentro sabiduría.",
    },
    "La Muerte": {
        "numero": 13,
        "nombre_rws": "La Muerte",
        "nombre_marsella": "La Mort",
        "nombre_thoth": "Death",
        "elemento": "agua",
        "planeta": "pluton",
        "signo": "escorpio",
        "letra_hebrea": "Nun",
        "palabras_clave": ["transformación", "fin de ciclo", "renacimiento", "cambio radical", "soltar"],
        "sombra": ["resistencia al cambio", "aferramiento", "miedo a lo desconocido", "estancamiento"],
        "pregunta_terapeutica": "¿Qué parte de ti, de tu vida o de tu identidad necesita morir para que puedas renacer?",
        "arquetipo": "Osiris / El Fenix",
        "afirmacion": "Doy la bienvenida a la transformación y confío en el renacimiento que le sigue.",
    },
    "La Templanza": {
        "numero": 14,
        "nombre_rws": "La Templanza",
        "nombre_marsella": "La Tempérance",
        "nombre_thoth": "Art",
        "elemento": "fuego",
        "planeta": "jupiter",
        "signo": "sagitario",
        "letra_hebrea": "Samekh",
        "palabras_clave": ["alquimia", "equilibrio", "moderación", "integración", "flujo"],
        "sombra": ["excesos", "desequilibrio", "impaciencia", "falta de armonía"],
        "pregunta_terapeutica": "¿Qué aspectos aparentemente contradictorios de tu vida necesitan ser integrados?",
        "arquetipo": "El Alquimista / Rafael",
        "afirmacion": "Integro mis opuestos internos y encuentro fluidez y equilibrio en mi vida.",
    },
    "El Diablo": {
        "numero": 15,
        "nombre_rws": "El Diablo",
        "nombre_marsella": "Le Diable",
        "nombre_thoth": "The Devil",
        "elemento": "tierra",
        "planeta": "saturno",
        "signo": "capricornio",
        "letra_hebrea": "Ayin",
        "palabras_clave": ["sombra", "adicción", "materialismo consciente", "poder", "sexualidad"],
        "sombra": ["esclavitud", "adicciones", "victimismo", "materialismo ciego", "control"],
        "pregunta_terapeutica": "¿Qué cadenas llevas voluntariamente que podrías soltar en cualquier momento?",
        "arquetipo": "Pan / La Sombra Junguiana",
        "afirmacion": "Reconozco mis sombras con compasión y elijo conscientemente mis ataduras.",
    },
    "La Torre": {
        "numero": 16,
        "nombre_rws": "La Torre",
        "nombre_marsella": "La Maison Dieu",
        "nombre_thoth": "The Tower",
        "elemento": "fuego",
        "planeta": "marte",
        "signo": "",
        "letra_hebrea": "Pe",
        "palabras_clave": ["liberación", "revelación", "crisis transformadora", "caída del ego", "ruptura"],
        "sombra": ["catástrofe evitable", "destrucción innecesaria", "ego que se resiste", "caos sin propósito"],
        "pregunta_terapeutica": "¿Qué estructura en tu vida está construida sobre bases falsas y necesita derrumbarse?",
        "arquetipo": "La Torre de Babel / El Rayo de Zeus",
        "afirmacion": "Las crisis me liberan de lo que ya no me sirve y abren espacio para algo verdadero.",
    },
    "La Estrella": {
        "numero": 17,
        "nombre_rws": "La Estrella",
        "nombre_marsella": "L'Étoile",
        "nombre_thoth": "The Star",
        "elemento": "aire",
        "planeta": "urano",
        "signo": "acuario",
        "letra_hebrea": "Tzaddi",
        "palabras_clave": ["esperanza", "inspiración", "sanación", "guía", "renovación"],
        "sombra": ["idealismo ingenuo", "evasión espiritual", "desilusión", "vulnerabilidad excesiva"],
        "pregunta_terapeutica": "¿Qué esperanza profunda llevas en tu interior que aún no has permitido que guíe tu camino?",
        "arquetipo": "Acuario / Hebe la sanadora",
        "afirmacion": "Mi luz interior me guía y traigo sanación y esperanza adonde voy.",
    },
    "La Luna": {
        "numero": 18,
        "nombre_rws": "La Luna",
        "nombre_marsella": "La Lune",
        "nombre_thoth": "The Moon",
        "elemento": "agua",
        "planeta": "luna",
        "signo": "piscis",
        "letra_hebrea": "Qoph",
        "palabras_clave": ["inconsciente", "ilusión", "sueños", "miedos profundos", "intuición onírica"],
        "sombra": ["miedo", "engaño", "confusión", "ilusiones", "miedos irracionales"],
        "pregunta_terapeutica": "¿Qué miedos del inconsciente están distorsionando tu percepción de la realidad?",
        "arquetipo": "Hécate / Selene",
        "afirmacion": "Navego mis profundidades con valentía y confío en mi capacidad de distinguir lo real.",
    },
    "El Sol": {
        "numero": 19,
        "nombre_rws": "El Sol",
        "nombre_marsella": "Le Soleil",
        "nombre_thoth": "The Sun",
        "elemento": "fuego",
        "planeta": "sol",
        "signo": "",
        "letra_hebrea": "Resh",
        "palabras_clave": ["alegría", "vitalidad", "claridad", "éxito", "autenticidad"],
        "sombra": ["arrogancia", "superficialidad", "exhibicionismo", "ingenuidad"],
        "pregunta_terapeutica": "¿Cuándo fue la última vez que brillaste con autenticidad sin preocuparte por lo que pensaban otros?",
        "arquetipo": "Apolo / El Niño Divino",
        "afirmacion": "Brillo con autenticidad y comparto mi luz con el mundo sin reservas.",
    },
    "El Juicio": {
        "numero": 20,
        "nombre_rws": "El Juicio",
        "nombre_marsella": "Le Jugement",
        "nombre_thoth": "The Aeon",
        "elemento": "fuego",
        "planeta": "pluton",
        "signo": "",
        "letra_hebrea": "Shin",
        "palabras_clave": ["despertar", "llamado", "renacimiento", "absolución", "evaluación"],
        "sombra": ["autojuicio excesivo", "negarse al llamado", "culpa no resuelta", "pasado que no suelta"],
        "pregunta_terapeutica": "¿Cuál es el llamado de tu alma que llevas tiempo ignorando?",
        "arquetipo": "El Día del Juicio / El Ángel Gabriel",
        "afirmacion": "Respondo al llamado de mi alma y me perdono por los capítulos que necesitaba vivir.",
    },
    "El Mundo": {
        "numero": 21,
        "nombre_rws": "El Mundo",
        "nombre_marsella": "Le Monde",
        "nombre_thoth": "The Universe",
        "elemento": "tierra",
        "planeta": "saturno",
        "signo": "",
        "letra_hebrea": "Tav",
        "palabras_clave": ["completitud", "integración", "logro", "plenitud", "totalidad"],
        "sombra": ["complacencia", "ciclo que no cierra", "perfeccionismo paralizante", "miedo al siguiente ciclo"],
        "pregunta_terapeutica": "¿Qué ciclo de tu vida has completado y qué nueva totalidad está emergiendo?",
        "arquetipo": "El Ser Completo / Androgino primordial",
        "afirmacion": "Celebro mi totalidad y la completitud de cada ciclo en mi vida.",
    },
}

# ─── Arcanos Menores ──────────────────────────────────────────────────────────

ARCANOS_MENORES: dict[str, dict] = {
    # ══ BASTOS ══
    "As de Bastos": {
        "palo": "bastos",
        "numero": 1,
        "elemento": "fuego",
        "palabras_clave": ["inicio", "inspiración", "potencial creativo", "chispa", "impulso"],
        "sombra": ["proyectos que no arrancan", "falsa partida", "exceso de energía sin dirección"],
        "pregunta_terapeutica": "¿Qué nuevo proyecto o impulso creativo sientes que está pugnando por nacer?",
    },
    "Dos de Bastos": {
        "palo": "bastos",
        "numero": 2,
        "elemento": "fuego",
        "palabras_clave": ["planificación", "visión", "espera activa", "poder personal", "expansión futura"],
        "sombra": ["impaciencia", "miedo al compromiso", "postergar la acción"],
        "pregunta_terapeutica": "¿Cuál es la visión a largo plazo que te impulsa pero aún no has comenzado a construir?",
    },
    "Tres de Bastos": {
        "palo": "bastos",
        "numero": 3,
        "elemento": "fuego",
        "palabras_clave": ["expansión", "colaboración", "visión cumplida parcialmente", "liderazgo", "horizonte"],
        "sombra": ["arrogancia prematura", "esperar resultados demasiado pronto", "dependencia de otros"],
        "pregunta_terapeutica": "¿Qué has logrado poner en marcha que ahora requiere paciencia y mirada larga?",
    },
    "Cuatro de Bastos": {
        "palo": "bastos",
        "numero": 4,
        "elemento": "fuego",
        "palabras_clave": ["celebración", "hogar", "estabilidad", "cosecha", "comunidad"],
        "sombra": ["complacencia", "resistencia al siguiente paso", "dependencia del grupo"],
        "pregunta_terapeutica": "¿Qué logro o etapa de tu vida mereces celebrar plenamente antes de seguir?",
    },
    "Cinco de Bastos": {
        "palo": "bastos",
        "numero": 5,
        "elemento": "fuego",
        "palabras_clave": ["competencia", "conflicto creativo", "dinamismo", "tensión productiva", "caos creativo"],
        "sombra": ["pelea innecesaria", "ego en conflicto", "falta de cooperación", "dispersión"],
        "pregunta_terapeutica": "¿Qué conflictos externos reflejan tu propio caos creativo interior?",
    },
    "Seis de Bastos": {
        "palo": "bastos",
        "numero": 6,
        "elemento": "fuego",
        "palabras_clave": ["victoria", "reconocimiento", "confianza", "liderazgo", "triunfo"],
        "sombra": ["arrogancia", "dependencia de la validación externa", "envidia ajena"],
        "pregunta_terapeutica": "¿Puedes reconocer tu propio éxito sin necesitar la validación de otros?",
    },
    "Siete de Bastos": {
        "palo": "bastos",
        "numero": 7,
        "elemento": "fuego",
        "palabras_clave": ["defensa", "perseverancia", "posición ganada", "resistencia", "valentía"],
        "sombra": ["paranoia", "defensividad excesiva", "combatividad innecesaria"],
        "pregunta_terapeutica": "¿Qué posición o logro tuyo vale la pena defender aunque cueste esfuerzo?",
    },
    "Ocho de Bastos": {
        "palo": "bastos",
        "numero": 8,
        "elemento": "fuego",
        "palabras_clave": ["velocidad", "movimiento", "mensajes", "acción rápida", "momentum"],
        "sombra": ["precipitación", "mensajes confusos", "impulsividad", "caos por velocidad"],
        "pregunta_terapeutica": "¿Qué situación está avanzando rápidamente y necesitas mantenerte enfocado/a?",
    },
    "Nueve de Bastos": {
        "palo": "bastos",
        "numero": 9,
        "elemento": "fuego",
        "palabras_clave": ["resistencia", "perseverancia final", "defensa", "casi al final", "fortaleza"],
        "sombra": ["agotamiento", "paranoia por cicatrices pasadas", "rigidez defensiva"],
        "pregunta_terapeutica": "¿Qué heridas del pasado te hacen estar en guardia cuando ya no es necesario?",
    },
    "Diez de Bastos": {
        "palo": "bastos",
        "numero": 10,
        "elemento": "fuego",
        "palabras_clave": ["responsabilidad", "carga", "compromiso", "completar", "esfuerzo final"],
        "sombra": ["sobrecarga", "martir", "incapacidad de delegar", "agotamiento por exceso"],
        "pregunta_terapeutica": "¿Qué cargas llevas que no son tuyas o que ya podrías soltar o delegar?",
    },
    "Paje de Bastos": {
        "palo": "bastos",
        "numero": 11,
        "elemento": "fuego",
        "palabras_clave": ["entusiasmo", "mensajes de aventura", "exploración", "potencial joven", "curiosidad"],
        "sombra": ["impulsividad sin foco", "superficialidad", "falta de seguimiento"],
        "pregunta_terapeutica": "¿Qué nuevo interés o llamado a la aventura está despertando en ti?",
    },
    "Caballero de Bastos": {
        "palo": "bastos",
        "numero": 12,
        "elemento": "fuego",
        "palabras_clave": ["acción", "pasión", "aventura", "ambición", "energía desbordante"],
        "sombra": ["imprudencia", "precipitación", "ego inflado", "inconstancia"],
        "pregunta_terapeutica": "¿Dónde necesitas canalizar tu pasión con más dirección y menos impulsividad?",
    },
    "Reina de Bastos": {
        "palo": "bastos",
        "numero": 13,
        "elemento": "fuego",
        "palabras_clave": ["carisma", "confianza", "liderazgo femenino", "determinación", "magnetismo"],
        "sombra": ["dominancia", "celos", "egocentrismo", "temperamento explosivo"],
        "pregunta_terapeutica": "¿Cómo puedes liderar desde tu carisma natural sin necesitar controlar a otros?",
    },
    "Rey de Bastos": {
        "palo": "bastos",
        "numero": 14,
        "elemento": "fuego",
        "palabras_clave": ["liderazgo visionario", "carisma maduro", "empresario", "inspiración", "autoridad creativa"],
        "sombra": ["impulsividad del líder", "intolerancia", "volatilidad", "arrogancia"],
        "pregunta_terapeutica": "¿Qué visión necesitas comenzar a liderar con madurez y convicción?",
    },
    # ══ COPAS ══
    "As de Copas": {
        "palo": "copas",
        "numero": 1,
        "elemento": "agua",
        "palabras_clave": ["amor nuevo", "abundancia emocional", "intuición", "apertura del corazón", "inicio espiritual"],
        "sombra": ["emociones reprimidas", "miedo a amar", "bloqueo afectivo"],
        "pregunta_terapeutica": "¿Tu corazón está abierto para recibir amor, tanto de otros como de ti mismo/a?",
    },
    "Dos de Copas": {
        "palo": "copas",
        "numero": 2,
        "elemento": "agua",
        "palabras_clave": ["unión", "atracción mutua", "partnership", "amor recíproco", "acuerdo emocional"],
        "sombra": ["codependencia", "relaciones tóxicas por costumbre", "conflicto velado"],
        "pregunta_terapeutica": "¿En tu relación más importante hay genuina reciprocidad y respeto mutuo?",
    },
    "Tres de Copas": {
        "palo": "copas",
        "numero": 3,
        "elemento": "agua",
        "palabras_clave": ["celebración", "amistad", "comunidad", "alegría compartida", "apoyo"],
        "sombra": ["excesos festivos", "chismes", "exclusión", "superficialidad social"],
        "pregunta_terapeutica": "¿Tienes una comunidad con la que celebrar y compartir las alegrías de la vida?",
    },
    "Cuatro de Copas": {
        "palo": "copas",
        "numero": 4,
        "elemento": "agua",
        "palabras_clave": ["introspección emocional", "meditación", "reevaluación", "contemplación", "descontento"],
        "sombra": ["apatía", "ingratitud", "ensimismamiento", "oportunidades ignoradas"],
        "pregunta_terapeutica": "¿Estás tan enfocado/a en lo que te falta que no ves lo que ya tienes?",
    },
    "Cinco de Copas": {
        "palo": "copas",
        "numero": 5,
        "elemento": "agua",
        "palabras_clave": ["pérdida", "duelo", "arrepentimiento", "tristeza consciente", "aprendizaje del dolor"],
        "sombra": ["victimismo", "duelo que no avanza", "incapacidad de ver lo que queda"],
        "pregunta_terapeutica": "¿Qué pérdida necesitas llorar completamente para poder ver lo que todavía tienes?",
    },
    "Seis de Copas": {
        "palo": "copas",
        "numero": 6,
        "elemento": "agua",
        "palabras_clave": ["nostalgia", "inocencia", "infancia", "generosidad", "recuerdos felices"],
        "sombra": ["vivir en el pasado", "idealización", "inmadurez emocional", "dependencia"],
        "pregunta_terapeutica": "¿Qué inocencia o alegría de tu infancia puedes traer al presente?",
    },
    "Siete de Copas": {
        "palo": "copas",
        "numero": 7,
        "elemento": "agua",
        "palabras_clave": ["ilusiones", "fantasías", "posibilidades", "elección", "imaginación"],
        "sombra": ["ilusiones confusas", "escapismo", "dificultad para elegir", "proyecciones"],
        "pregunta_terapeutica": "¿Cuáles de tus deseos son ilusiones y cuáles son llamados genuinos de tu alma?",
    },
    "Ocho de Copas": {
        "palo": "copas",
        "numero": 8,
        "elemento": "agua",
        "palabras_clave": ["partir", "buscar más", "dejar atrás", "llamado espiritual", "desolación productiva"],
        "sombra": ["abandono por miedo", "huir de problemas", "soledad autoimpuesta"],
        "pregunta_terapeutica": "¿Qué situación cómoda pero vacía necesitas abandonar para buscar algo más profundo?",
    },
    "Nueve de Copas": {
        "palo": "copas",
        "numero": 9,
        "elemento": "agua",
        "palabras_clave": ["deseos cumplidos", "satisfacción", "bienestar", "plenitud", "el deseo del corazón"],
        "sombra": ["complacencia", "superficialidad del deseo", "deseos del ego no del alma"],
        "pregunta_terapeutica": "¿Qué deseo del corazón genuino mereces permitirte manifestar?",
    },
    "Diez de Copas": {
        "palo": "copas",
        "numero": 10,
        "elemento": "agua",
        "palabras_clave": ["felicidad familiar", "armonía", "plenitud emocional", "hogar", "amor duradero"],
        "sombra": ["expectativas irreales de perfección", "disfunción oculta", "miedo a la felicidad"],
        "pregunta_terapeutica": "¿Qué tipo de vida familiar o emocional deseas construir y qué necesitas para ello?",
    },
    "Paje de Copas": {
        "palo": "copas",
        "numero": 11,
        "elemento": "agua",
        "palabras_clave": ["mensajes del corazón", "intuición joven", "creatividad emocional", "apertura", "sueños"],
        "sombra": ["inmadurez emocional", "fantasías sin raíz", "susceptibilidad"],
        "pregunta_terapeutica": "¿Qué mensaje intuitivo de tu corazón has estado ignorando por parecerte demasiado simple?",
    },
    "Caballero de Copas": {
        "palo": "copas",
        "numero": 12,
        "elemento": "agua",
        "palabras_clave": ["romanticismo", "quijotismo", "invitación emocional", "sensibilidad", "idealismo"],
        "sombra": ["seducción sin profundidad", "inmadurez romántica", "promesas incumplidas"],
        "pregunta_terapeutica": "¿Dónde estás siendo un soñador romántico en lugar de comprometerte de verdad?",
    },
    "Reina de Copas": {
        "palo": "copas",
        "numero": 13,
        "elemento": "agua",
        "palabras_clave": ["empatía", "intuición profunda", "maternidad emocional", "compasión", "sanación"],
        "sombra": ["sobreprotección", "ahogar con amor", "absorber emociones ajenas", "codependencia"],
        "pregunta_terapeutica": "¿Cómo puedes cuidar a otros desde tu propia plenitud emocional, no desde el vacío?",
    },
    "Rey de Copas": {
        "palo": "copas",
        "numero": 14,
        "elemento": "agua",
        "palabras_clave": ["madurez emocional", "sabiduría afectiva", "compasión madura", "equilibrio emocional", "diplomacia"],
        "sombra": ["represión emocional", "manipulación a través de la emoción", "frialdad disfrazada"],
        "pregunta_terapeutica": "¿Puedes guiar a otros con compasión sin perder tu propio equilibrio emocional?",
    },
    # ══ ESPADAS ══
    "As de Espadas": {
        "palo": "espadas",
        "numero": 1,
        "elemento": "aire",
        "palabras_clave": ["verdad", "claridad mental", "nuevo comienzo intelectual", "breakthrough", "justicia"],
        "sombra": ["crueldad con la verdad", "uso del intelecto para herir", "pensamiento destructivo"],
        "pregunta_terapeutica": "¿Qué verdad necesitas reconocer con claridad, sin suavizarla más?",
    },
    "Dos de Espadas": {
        "palo": "espadas",
        "numero": 2,
        "elemento": "aire",
        "palabras_clave": ["decisión difícil", "punto muerto", "equilibrio precario", "bloqueo", "dilema"],
        "sombra": ["negación", "parálisis por análisis", "evitar decidir", "autoengaño"],
        "pregunta_terapeutica": "¿Qué estás evitando ver o decidir porque la verdad te parece demasiado incómoda?",
    },
    "Tres de Espadas": {
        "palo": "espadas",
        "numero": 3,
        "elemento": "aire",
        "palabras_clave": ["dolor", "ruptura", "traición", "duelo", "separación necesaria"],
        "sombra": ["herida crónica", "victimismo", "regodearse en el dolor"],
        "pregunta_terapeutica": "¿Qué dolor del corazón todavía no has permitido que sane completamente?",
    },
    "Cuatro de Espadas": {
        "palo": "espadas",
        "numero": 4,
        "elemento": "aire",
        "palabras_clave": ["descanso", "recuperación", "meditación", "retiro", "preparación"],
        "sombra": ["evitación", "escapismo", "estancamiento disfrazado de descanso"],
        "pregunta_terapeutica": "¿Necesitas realmente descansar y recuperarte antes de tu próximo movimiento?",
    },
    "Cinco de Espadas": {
        "palo": "espadas",
        "numero": 5,
        "elemento": "aire",
        "palabras_clave": ["conflicto", "victoria pírrica", "derrota consciente", "límites", "retirada estratégica"],
        "sombra": ["ganar a cualquier costo", "humillar a otros", "combatividad ego"],
        "pregunta_terapeutica": "¿Qué batallas estás peleando que no valen la pena de ganar?",
    },
    "Seis de Espadas": {
        "palo": "espadas",
        "numero": 6,
        "elemento": "aire",
        "palabras_clave": ["transición", "viaje", "alejarse del conflicto", "esperanza tranquila", "sanación gradual"],
        "sombra": ["huir sin resolver", "llevar el peso del pasado al presente"],
        "pregunta_terapeutica": "¿Estás transitando hacia algo nuevo o simplemente huyendo de algo viejo?",
    },
    "Siete de Espadas": {
        "palo": "espadas",
        "numero": 7,
        "elemento": "aire",
        "palabras_clave": ["estrategia", "diplomacia", "ingenio", "movimiento calculado", "escape táctico"],
        "sombra": ["engaño", "deshonestidad", "robo de ideas", "evasión irresponsable"],
        "pregunta_terapeutica": "¿Estás siendo estratégico o estás engañando a alguien (incluido a ti mismo)?",
    },
    "Ocho de Espadas": {
        "palo": "espadas",
        "numero": 8,
        "elemento": "aire",
        "palabras_clave": ["limitación autopercibida", "bloqueo mental", "victimismo", "restricción", "miedo paralizante"],
        "sombra": ["prisión mental", "creencias limitantes rígidas", "negarse a ver salidas"],
        "pregunta_terapeutica": "¿Qué creencias mentales te tienen atado/a cuando en realidad podrías moverte libremente?",
    },
    "Nueve de Espadas": {
        "palo": "espadas",
        "numero": 9,
        "elemento": "aire",
        "palabras_clave": ["ansiedad", "pesadillas", "culpa", "preocupación excesiva", "mente nocturna"],
        "sombra": ["tortura mental", "catastrofismo", "insomnio emocional", "culpa sin perdón"],
        "pregunta_terapeutica": "¿Qué pensamientos nocturnos te torturan y qué verdad ocultan?",
    },
    "Diez de Espadas": {
        "palo": "espadas",
        "numero": 10,
        "elemento": "aire",
        "palabras_clave": ["fin doloroso", "derrota total", "punto de quiebre", "rock bottom", "nuevo amanecer"],
        "sombra": ["victimismo extremo", "dramatismo", "negarse a levantarse"],
        "pregunta_terapeutica": "¿Qué ciclo de pensamiento o situación ha llegado a su fin absoluto, dejando espacio para renacer?",
    },
    "Paje de Espadas": {
        "palo": "espadas",
        "numero": 11,
        "elemento": "aire",
        "palabras_clave": ["curiosidad mental", "vigilancia", "mensajes intelectuales", "aprendizaje rápido", "ingenio"],
        "sombra": ["chismorreo", "espionaje", "inmadurez mental", "agresividad verbal"],
        "pregunta_terapeutica": "¿Qué información o conocimiento necesitas buscar con más curiosidad y menos prejuicio?",
    },
    "Caballero de Espadas": {
        "palo": "espadas",
        "numero": 12,
        "elemento": "aire",
        "palabras_clave": ["acción intelectual", "directness", "velocidad mental", "determinación", "coraje"],
        "sombra": ["precipitación", "crueldad verbal", "no escuchar", "atropellar con ideas"],
        "pregunta_terapeutica": "¿Estás tan seguro/a de tu verdad que no dejas espacio para escuchar otras perspectivas?",
    },
    "Reina de Espadas": {
        "palo": "espadas",
        "numero": 13,
        "elemento": "aire",
        "palabras_clave": ["claridad mental", "independencia", "discernimiento", "honestidad directa", "sabiduría del dolor"],
        "sombra": ["frialdad", "crueldad con la verdad", "distancia emocional", "amargura"],
        "pregunta_terapeutica": "¿Cómo puedes decir tu verdad con claridad sin perder la compasión?",
    },
    "Rey de Espadas": {
        "palo": "espadas",
        "numero": 14,
        "elemento": "aire",
        "palabras_clave": ["autoridad intelectual", "justicia", "liderazgo mental", "ética", "toma de decisiones"],
        "sombra": ["tiranía intelectual", "frialdad clínica", "inflexibilidad moral", "autoritarismo"],
        "pregunta_terapeutica": "¿Puedes ejercer tu autoridad e inteligencia al servicio del bien común, no solo del tuyo?",
    },
    # ══ PENTÁCULOS ══
    "As de Pentáculos": {
        "palo": "pentaculos",
        "numero": 1,
        "elemento": "tierra",
        "palabras_clave": ["nueva oportunidad material", "prosperidad", "semilla de abundancia", "manifestación", "potencial práctico"],
        "sombra": ["codicia", "oportunidad desaprovechada", "materialismo vacío"],
        "pregunta_terapeutica": "¿Qué nueva oportunidad material o práctica se está presentando en tu vida?",
    },
    "Dos de Pentáculos": {
        "palo": "pentaculos",
        "numero": 2,
        "elemento": "tierra",
        "palabras_clave": ["equilibrio", "malabarismo", "adaptabilidad", "cambio fluido", "gestión de recursos"],
        "sombra": ["inestabilidad", "demasiados platos en el aire", "falta de foco financiero"],
        "pregunta_terapeutica": "¿Cómo estás equilibrando las distintas demandas y responsabilidades de tu vida?",
    },
    "Tres de Pentáculos": {
        "palo": "pentaculos",
        "numero": 3,
        "elemento": "tierra",
        "palabras_clave": ["maestría", "colaboración", "artesanía", "reconocimiento del trabajo", "aprendizaje"],
        "sombra": ["mediocridad", "falta de reconocimiento", "conflicto en el equipo"],
        "pregunta_terapeutica": "¿Estás aplicando tu maestría y colaborando con otros para construir algo duradero?",
    },
    "Cuatro de Pentáculos": {
        "palo": "pentaculos",
        "numero": 4,
        "elemento": "tierra",
        "palabras_clave": ["seguridad", "ahorro", "control de recursos", "estabilidad", "posesión"],
        "sombra": ["avaricia", "control excesivo", "miedo a perder", "bloqueo del flujo"],
        "pregunta_terapeutica": "¿El miedo a perder lo que tienes te está impidiendo crecer y compartir?",
    },
    "Cinco de Pentáculos": {
        "palo": "pentaculos",
        "numero": 5,
        "elemento": "tierra",
        "palabras_clave": ["dificultad material", "soledad", "crisis", "exclusión", "escasez percibida"],
        "sombra": ["pobreza de conciencia", "victimismo material", "aislar en la dificultad"],
        "pregunta_terapeutica": "¿En qué área de tu vida te sientes excluido/a o en escasez, y hay ayuda disponible que no estás viendo?",
    },
    "Seis de Pentáculos": {
        "palo": "pentaculos",
        "numero": 6,
        "elemento": "tierra",
        "palabras_clave": ["generosidad", "dar y recibir", "caridad", "equilibrio de poder", "flujo de recursos"],
        "sombra": ["condescendencia", "deuda de favores", "dar para controlar", "incapacidad de recibir"],
        "pregunta_terapeutica": "¿Hay equilibrio entre lo que das y lo que recibes en tu vida material y afectiva?",
    },
    "Siete de Pentáculos": {
        "palo": "pentaculos",
        "numero": 7,
        "elemento": "tierra",
        "palabras_clave": ["inversión a largo plazo", "paciencia", "evaluación del progreso", "cultivo", "espera fértil"],
        "sombra": ["impaciencia", "rendirse antes de la cosecha", "esfuerzo sin dirección"],
        "pregunta_terapeutica": "¿Estás dispuesto/a a invertir tiempo y paciencia en proyectos que dan frutos a largo plazo?",
    },
    "Ocho de Pentáculos": {
        "palo": "pentaculos",
        "numero": 8,
        "elemento": "tierra",
        "palabras_clave": ["diligencia", "maestría en progreso", "artesanía", "dedicación", "aprendizaje continuo"],
        "sombra": ["perfeccionismo paralizante", "trabajo compulsivo", "enfoque sin visión"],
        "pregunta_terapeutica": "¿Estás dedicando tu esfuerzo al desarrollo de tu verdadera maestría o simplemente ocupando el tiempo?",
    },
    "Nueve de Pentáculos": {
        "palo": "pentaculos",
        "numero": 9,
        "elemento": "tierra",
        "palabras_clave": ["independencia", "abundancia merecida", "lujo", "autosufiencia", "refinamiento"],
        "sombra": ["soledad en la abundancia", "materialismo vacío", "aislamiento por autosuficiencia"],
        "pregunta_terapeutica": "¿Puedes disfrutar de lo que has construido con orgullo genuino sin necesitar la aprobación de otros?",
    },
    "Diez de Pentáculos": {
        "palo": "pentaculos",
        "numero": 10,
        "elemento": "tierra",
        "palabras_clave": ["legado", "riqueza familiar", "abundancia permanente", "herencia", "seguridad generacional"],
        "sombra": ["privilegio ignorado", "peso de la herencia familiar", "estancamiento en tradición"],
        "pregunta_terapeutica": "¿Qué legado material, emocional o espiritual deseas dejar a quienes vienen después de ti?",
    },
    "Paje de Pentáculos": {
        "palo": "pentaculos",
        "numero": 11,
        "elemento": "tierra",
        "palabras_clave": ["estudio", "nuevo proyecto práctico", "diligencia joven", "aprendizaje", "curiosidad material"],
        "sombra": ["falta de ambición", "exceso de cautela", "lentitud paralizante"],
        "pregunta_terapeutica": "¿Qué habilidad o conocimiento práctico necesitas empezar a desarrollar con paciencia?",
    },
    "Caballero de Pentáculos": {
        "palo": "pentaculos",
        "numero": 12,
        "elemento": "tierra",
        "palabras_clave": ["trabajo duro", "confiabilidad", "paciencia", "metódico", "perseverancia"],
        "sombra": ["exceso de cautela", "terquedad", "resistencia al cambio", "aburrimiento"],
        "pregunta_terapeutica": "¿Estás avanzando con persistencia hacia tus metas o estás atascado en la rutina?",
    },
    "Reina de Pentáculos": {
        "palo": "pentaculos",
        "numero": 13,
        "elemento": "tierra",
        "palabras_clave": ["nutrición", "abundancia práctica", "maternidad material", "bienestar", "sentido práctico"],
        "sombra": ["materialismo excesivo", "sobreprotección", "dependencia económica", "apego"],
        "pregunta_terapeutica": "¿Cómo nutres tu entorno y creas seguridad material desde un lugar de abundancia interna?",
    },
    "Rey de Pentáculos": {
        "palo": "pentaculos",
        "numero": 14,
        "elemento": "tierra",
        "palabras_clave": ["éxito material", "madurez financiera", "liderazgo práctico", "abundancia estable", "generosidad del rey"],
        "sombra": ["materialismo excesivo", "corrupción", "frialdad por riqueza", "control a través del dinero"],
        "pregunta_terapeutica": "¿Estás usando tu estabilidad material y tu éxito para el bienestar de quienes te rodean?",
    },
}

# ─── Tiradas ──────────────────────────────────────────────────────────────────

TIRADAS: dict[str, dict] = {
    "carta_del_dia": {
        "nombre": "Carta del Día",
        "num_cartas": 1,
        "descripcion": "Una sola carta que ofrece la energía, mensaje o tema principal del día. Ideal para práctica diaria de consciencia.",
        "posiciones": [
            {"id": 1, "nombre": "Carta del día", "descripcion": "Energía, mensaje o tema que rige el día"},
        ],
        "fuente": "Tradición universal del tarot",
        "enfoque": "orientativo",
    },
    "tres_cartas": {
        "nombre": "Tres Cartas: Pasado / Presente / Futuro",
        "num_cartas": 3,
        "descripcion": "La tirada más clásica. Tres cartas que ofrecen una visión narrativa del flujo temporal de una situación.",
        "posiciones": [
            {"id": 1, "nombre": "Pasado", "descripcion": "Lo que ha influido y llevado a la situación actual"},
            {"id": 2, "nombre": "Presente", "descripcion": "La energía y circunstancias del momento"},
            {"id": 3, "nombre": "Futuro / Potencial", "descripcion": "La dirección hacia la que apunta la energía si sigue el curso actual"},
        ],
        "fuente": "Tradición clásica del tarot",
        "enfoque": "narrativo",
    },
    "cruz_simple": {
        "nombre": "Cruz Simple (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Una cruz de cinco cartas que examina la situación central desde múltiples ángulos: arriba, abajo, izquierda, derecha y centro.",
        "posiciones": [
            {"id": 1, "nombre": "Centro — La situación", "descripcion": "El corazón del asunto, la energía central"},
            {"id": 2, "nombre": "Arriba — Influencia consciente", "descripcion": "Lo que está en la mente consciente, aspiraciones"},
            {"id": 3, "nombre": "Abajo — Influencia inconsciente", "descripcion": "Lo que subyace, raíces ocultas, el inconsciente"},
            {"id": 4, "nombre": "Izquierda — Pasado / Lo que se va", "descripcion": "Lo que está quedando atrás"},
            {"id": 5, "nombre": "Derecha — Futuro / Lo que viene", "descripcion": "La dirección hacia la que se mueve la energía"},
        ],
        "fuente": "Tradición del tarot clásico",
        "enfoque": "narrativo",
    },
    "herradura": {
        "nombre": "Herradura (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Tirada en forma de herradura que proporciona una visión completa de una situación a lo largo del tiempo con consejo.",
        "posiciones": [
            {"id": 1, "nombre": "Pasado distante", "descripcion": "Influencias del pasado lejano que moldean la situación"},
            {"id": 2, "nombre": "Pasado reciente", "descripcion": "Eventos recientes que han llevado al presente"},
            {"id": 3, "nombre": "Presente", "descripcion": "La situación tal como es ahora"},
            {"id": 4, "nombre": "Futuro próximo", "descripcion": "Lo que se aproxima en el corto plazo"},
            {"id": 5, "nombre": "Influencias externas", "descripcion": "Personas o fuerzas del entorno que influyen"},
            {"id": 6, "nombre": "Esperanzas y miedos", "descripcion": "Lo que se espera o se teme inconscientemente"},
            {"id": 7, "nombre": "Resultado probable", "descripcion": "El desenlace más probable si la energía sigue su curso"},
        ],
        "fuente": "Tradición esotérica occidental",
        "enfoque": "narrativo",
    },
    "chakras": {
        "nombre": "Tirada de los Chakras (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Cada carta representa un chakra del sistema energético. Revela bloqueos, excesos y potenciales en cada centro de energía.",
        "posiciones": [
            {"id": 1, "nombre": "Muladhara — Raíz", "descripcion": "Seguridad, base material, supervivencia, conexión con la tierra"},
            {"id": 2, "nombre": "Svadhisthana — Sacro", "descripcion": "Creatividad, sexualidad, emociones, placer"},
            {"id": 3, "nombre": "Manipura — Plexo Solar", "descripcion": "Poder personal, voluntad, autoestima, acción"},
            {"id": 4, "nombre": "Anahata — Corazón", "descripcion": "Amor, compasión, relaciones, integración"},
            {"id": 5, "nombre": "Vishuddha — Garganta", "descripcion": "Comunicación, expresión, verdad, creatividad verbal"},
            {"id": 6, "nombre": "Ajna — Tercer Ojo", "descripcion": "Intuición, claridad, visión, insight"},
            {"id": 7, "nombre": "Sahasrara — Corona", "descripcion": "Espiritualidad, conexión con lo Divino, propósito superior"},
        ],
        "fuente": "Integración tarot-yoga/vedanta",
        "enfoque": "chakras",
    },
    "cruz_celtica": {
        "nombre": "Cruz Céltica (10 cartas)",
        "num_cartas": 10,
        "descripcion": "La tirada más completa y detallada del tarot clásico. Diez cartas que examinan una situación desde todos sus ángulos posibles.",
        "posiciones": [
            {"id": 1, "nombre": "El consultante / La situación", "descripcion": "La persona y su situación central"},
            {"id": 2, "nombre": "El obstáculo / La cruz", "descripcion": "Lo que se interpone o complementa la situación"},
            {"id": 3, "nombre": "La corona — Lo consciente", "descripcion": "Lo que está en la mente, el ideal o meta"},
            {"id": 4, "nombre": "La base — Lo inconsciente", "descripcion": "Las raíces ocultas, lo que subyace"},
            {"id": 5, "nombre": "El pasado reciente", "descripcion": "Lo que está quedando atrás"},
            {"id": 6, "nombre": "El futuro próximo", "descripcion": "Lo que se acerca en el corto plazo"},
            {"id": 7, "nombre": "El consultante en situación", "descripcion": "Cómo se ve a sí mismo/a en esta situación"},
            {"id": 8, "nombre": "Las influencias externas", "descripcion": "El entorno, otras personas, fuerzas externas"},
            {"id": 9, "nombre": "Esperanzas y miedos", "descripcion": "Los deseos más profundos y los temores ocultos"},
            {"id": 10, "nombre": "El resultado final", "descripcion": "El desenlace probable si la energía continúa su curso"},
        ],
        "fuente": "A.E. Waite, The Pictorial Key to the Tarot (1910)",
        "enfoque": "terapeutico",
    },
    "cinco_centros": {
        "nombre": "Los Cinco Centros — Jodorowsky (15 cartas)",
        "num_cartas": 15,
        "descripcion": "Método psicomágico de Alejandro Jodorowsky. Quince cartas organizadas en cinco grupos que representan los centros del ser: material, sexual, emocional, creativo y espiritual.",
        "posiciones": [
            {"id": 1,  "nombre": "Centro Material 1 — Pasado", "descripcion": "Historia material y de supervivencia del pasado"},
            {"id": 2,  "nombre": "Centro Material 2 — Presente", "descripcion": "Situación material actual"},
            {"id": 3,  "nombre": "Centro Material 3 — Futuro potencial", "descripcion": "Dirección material futura"},
            {"id": 4,  "nombre": "Centro Sexual 1 — Pasado", "descripcion": "Historia creativa y sexual del pasado"},
            {"id": 5,  "nombre": "Centro Sexual 2 — Presente", "descripcion": "Creatividad y sexualidad actual"},
            {"id": 6,  "nombre": "Centro Sexual 3 — Futuro potencial", "descripcion": "Potencial creativo-sexual futuro"},
            {"id": 7,  "nombre": "Centro Emocional 1 — Pasado", "descripcion": "Historia emocional y afectiva"},
            {"id": 8,  "nombre": "Centro Emocional 2 — Presente", "descripcion": "Estado emocional presente"},
            {"id": 9,  "nombre": "Centro Emocional 3 — Futuro potencial", "descripcion": "Potencial emocional futuro"},
            {"id": 10, "nombre": "Centro Creativo 1 — Pasado", "descripcion": "Historia expresiva y comunicativa"},
            {"id": 11, "nombre": "Centro Creativo 2 — Presente", "descripcion": "Expresión creativa actual"},
            {"id": 12, "nombre": "Centro Creativo 3 — Futuro potencial", "descripcion": "Potencial creativo-expresivo futuro"},
            {"id": 13, "nombre": "Centro Espiritual 1 — Pasado", "descripcion": "Historia espiritual y de sentido"},
            {"id": 14, "nombre": "Centro Espiritual 2 — Presente", "descripcion": "Vida espiritual y de propósito actual"},
            {"id": 15, "nombre": "Centro Espiritual 3 — Síntesis", "descripcion": "Síntesis y potencial espiritual último"},
        ],
        "fuente": "Alejandro Jodorowsky, El Camino del Tarot (2004)",
        "enfoque": "terapeutico",
    },
}

# ─── Layout (coordenadas %) de cada posición, para acomodar las cartas ───────
_LAYOUTS: dict[str, list] = {
    "carta_del_dia": [(50, 42)],
    "tres_cartas":   [(22, 50), (50, 50), (78, 50)],
    "cruz_simple":   [(50, 50), (50, 16), (50, 84), (20, 50), (80, 50)],
    "herradura":     [(12, 74), (22, 44), (37, 24), (50, 18), (63, 24), (78, 44), (88, 74)],
    "chakras":       [(50, 93), (50, 80), (50, 67), (50, 54), (50, 41), (50, 28), (50, 11)],
    "cruz_celtica":  [(34, 50), (34, 50), (34, 20), (34, 80), (15, 50), (53, 50), (82, 85), (82, 62), (82, 39), (82, 16)],
    "cinco_centros": [(11, 28), (11, 50), (11, 72), (30, 28), (30, 50), (30, 72), (50, 28), (50, 50), (50, 72),
                      (70, 28), (70, 50), (70, 72), (89, 28), (89, 50), (89, 72)],
}
for _tid, _coords in _LAYOUTS.items():
    for _pos, _xy in zip(TIRADAS[_tid]["posiciones"], _coords):
        _pos["x"], _pos["y"] = _xy[0], _xy[1]
TIRADAS["cruz_celtica"]["posiciones"][1]["rot"] = True  # carta 2 cruzada

# ─── Tiradas adicionales (con geometría y propósito) ─────────────────────────
TIRADAS.update({
    "espejo_relacion": {
        "nombre": "Espejo de la Relación (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Para explorar un vínculo de pareja o relación: cómo está cada parte, qué aporta, el obstáculo y hacia dónde va.",
        "posiciones": [
            {"id": 1, "nombre": "Tú", "descripcion": "Cómo estás tú en la relación", "x": 24, "y": 30},
            {"id": 2, "nombre": "La otra persona", "descripcion": "Cómo está la otra persona", "x": 76, "y": 30},
            {"id": 3, "nombre": "El vínculo", "descripcion": "La energía de la relación en sí", "x": 50, "y": 50},
            {"id": 4, "nombre": "Lo que tú aportas", "descripcion": "Lo que tú llevas al vínculo", "x": 24, "y": 70},
            {"id": 5, "nombre": "Lo que aporta el otro", "descripcion": "Lo que la otra persona lleva", "x": 76, "y": 70},
            {"id": 6, "nombre": "El obstáculo / la lección", "descripcion": "El reto a trabajar juntos", "x": 50, "y": 20},
            {"id": 7, "nombre": "Hacia dónde va", "descripcion": "El potencial o dirección del vínculo", "x": 50, "y": 82},
        ],
        "fuente": "Tradición del tarot relacional", "enfoque": "relacional",
    },
    "decision": {
        "nombre": "La Decisión — Dos Caminos (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Cuando hay que elegir entre dos opciones: muestra cada camino y su resultado probable.",
        "posiciones": [
            {"id": 1, "nombre": "La encrucijada", "descripcion": "La situación que exige decidir", "x": 50, "y": 50},
            {"id": 2, "nombre": "Camino A", "descripcion": "La naturaleza de la primera opción", "x": 25, "y": 26},
            {"id": 3, "nombre": "Resultado de A", "descripcion": "Adónde lleva la primera opción", "x": 25, "y": 74},
            {"id": 4, "nombre": "Camino B", "descripcion": "La naturaleza de la segunda opción", "x": 75, "y": 26},
            {"id": 5, "nombre": "Resultado de B", "descripcion": "Adónde lleva la segunda opción", "x": 75, "y": 74},
        ],
        "fuente": "Tradición del tarot práctico", "enfoque": "decision",
    },
    "rueda_del_anio": {
        "nombre": "Rueda del Año (13 cartas)",
        "num_cartas": 13,
        "descripcion": "Una carta para el tema del año y una por cada uno de los doce meses. Ideal para inicios de ciclo.",
        "posiciones": [
            {"id": 1, "nombre": "Tema del año", "descripcion": "La energía rectora del ciclo", "x": 50, "y": 50},
            {"id": 2, "nombre": "Mes 1", "descripcion": "Primer mes del ciclo", "x": 50, "y": 9},
            {"id": 3, "nombre": "Mes 2", "descripcion": "Segundo mes", "x": 70, "y": 15},
            {"id": 4, "nombre": "Mes 3", "descripcion": "Tercer mes", "x": 85, "y": 30},
            {"id": 5, "nombre": "Mes 4", "descripcion": "Cuarto mes", "x": 91, "y": 50},
            {"id": 6, "nombre": "Mes 5", "descripcion": "Quinto mes", "x": 85, "y": 70},
            {"id": 7, "nombre": "Mes 6", "descripcion": "Sexto mes", "x": 70, "y": 85},
            {"id": 8, "nombre": "Mes 7", "descripcion": "Séptimo mes", "x": 50, "y": 91},
            {"id": 9, "nombre": "Mes 8", "descripcion": "Octavo mes", "x": 30, "y": 85},
            {"id": 10, "nombre": "Mes 9", "descripcion": "Noveno mes", "x": 15, "y": 70},
            {"id": 11, "nombre": "Mes 10", "descripcion": "Décimo mes", "x": 9, "y": 50},
            {"id": 12, "nombre": "Mes 11", "descripcion": "Undécimo mes", "x": 15, "y": 30},
            {"id": 13, "nombre": "Mes 12", "descripcion": "Duodécimo mes", "x": 30, "y": 15},
        ],
        "fuente": "Tradición del tarot predictivo", "enfoque": "ciclico",
    },
    "sombra": {
        "nombre": "Trabajo de Sombra (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Para integrar aspectos negados de uno mismo: la máscara, la sombra, su origen, el don oculto y la integración.",
        "posiciones": [
            {"id": 1, "nombre": "La máscara", "descripcion": "Lo que muestras al mundo", "x": 50, "y": 16},
            {"id": 2, "nombre": "La sombra", "descripcion": "Lo que ocultas o niegas", "x": 50, "y": 48},
            {"id": 3, "nombre": "El origen", "descripcion": "De dónde viene esa sombra", "x": 25, "y": 72},
            {"id": 4, "nombre": "El don oculto", "descripcion": "El recurso que la sombra esconde", "x": 75, "y": 72},
            {"id": 5, "nombre": "La integración", "descripcion": "Cómo integrarla para sanar", "x": 50, "y": 90},
        ],
        "fuente": "Tarot terapéutico junguiano", "enfoque": "terapeutico",
    },
    "arbol_vida": {
        "nombre": "Árbol de la Vida (10 cartas)",
        "num_cartas": 10,
        "descripcion": "Las diez sefirot del Árbol de la Vida cabalístico: una lectura espiritual integral del consultante.",
        "posiciones": [
            {"id": 1, "nombre": "Kether — Propósito", "descripcion": "La chispa, el propósito superior", "x": 50, "y": 8},
            {"id": 2, "nombre": "Chokmah — Sabiduría", "descripcion": "La fuerza creadora, la visión", "x": 72, "y": 21},
            {"id": 3, "nombre": "Binah — Entendimiento", "descripcion": "La forma, la comprensión profunda", "x": 28, "y": 21},
            {"id": 4, "nombre": "Chesed — Misericordia", "descripcion": "La expansión, la generosidad", "x": 72, "y": 41},
            {"id": 5, "nombre": "Geburah — Rigor", "descripcion": "La disciplina, los límites", "x": 28, "y": 41},
            {"id": 6, "nombre": "Tiphareth — Belleza", "descripcion": "El corazón, el equilibrio, el yo", "x": 50, "y": 51},
            {"id": 7, "nombre": "Netzach — Victoria", "descripcion": "Las emociones, los deseos", "x": 72, "y": 68},
            {"id": 8, "nombre": "Hod — Gloria", "descripcion": "La mente, la comunicación", "x": 28, "y": 68},
            {"id": 9, "nombre": "Yesod — Fundamento", "descripcion": "El inconsciente, los sueños", "x": 50, "y": 78},
            {"id": 10, "nombre": "Malkuth — Reino", "descripcion": "La materia, el cuerpo, lo cotidiano", "x": 50, "y": 92},
        ],
        "fuente": "Tarot cabalístico (Golden Dawn)", "enfoque": "espiritual",
    },
    "si_o_no": {
        "nombre": "Sí o No (3 cartas)",
        "num_cartas": 3,
        "descripcion": "Para una pregunta concreta de sí o no: la respuesta central y las fuerzas a favor y en contra.",
        "posiciones": [
            {"id": 1, "nombre": "La respuesta", "descripcion": "La tendencia central de la respuesta", "x": 50, "y": 38},
            {"id": 2, "nombre": "Lo que apoya", "descripcion": "Fuerzas a favor", "x": 27, "y": 66},
            {"id": 3, "nombre": "Lo que limita", "descripcion": "Fuerzas en contra", "x": 73, "y": 66},
        ],
        "fuente": "Tradición del tarot práctico", "enfoque": "orientativo",
    },
    "cuerpo_mente_espiritu": {
        "nombre": "Cuerpo · Mente · Espíritu (3 cartas)",
        "num_cartas": 3,
        "descripcion": "Una lectura de bienestar integral: el estado del cuerpo, de la mente y del espíritu.",
        "posiciones": [
            {"id": 1, "nombre": "Cuerpo", "descripcion": "El estado físico y material", "x": 25, "y": 50},
            {"id": 2, "nombre": "Mente", "descripcion": "El estado mental y emocional", "x": 50, "y": 50},
            {"id": 3, "nombre": "Espíritu", "descripcion": "El estado espiritual y de propósito", "x": 75, "y": 50},
        ],
        "fuente": "Tarot holístico", "enfoque": "bienestar",
    },
    "proposito_alma": {
        "nombre": "Propósito del Alma (6 cartas)",
        "num_cartas": 6,
        "descripcion": "Para reconectar con el sentido de vida: quién eres, tu don, tu herida, tu propósito, el obstáculo y el siguiente paso.",
        "posiciones": [
            {"id": 1, "nombre": "Quién eres ahora", "descripcion": "Tu punto de partida", "x": 50, "y": 82},
            {"id": 2, "nombre": "Tu don", "descripcion": "El talento que traes", "x": 24, "y": 56},
            {"id": 3, "nombre": "Tu herida", "descripcion": "Lo que duele y enseña", "x": 76, "y": 56},
            {"id": 4, "nombre": "Tu propósito", "descripcion": "Hacia dónde apunta tu alma", "x": 50, "y": 38},
            {"id": 5, "nombre": "El obstáculo", "descripcion": "Lo que debes trascender", "x": 24, "y": 20},
            {"id": 6, "nombre": "El siguiente paso", "descripcion": "La acción concreta ahora", "x": 76, "y": 20},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
})

# ─── Catálogo ampliado (canon clásico, cada una con geometría y caso de uso) ──
TIRADAS.update({
    "situacion_consejo": {
        "nombre": "Situación · Obstáculo · Consejo (3 cartas)",
        "num_cartas": 3,
        "descripcion": "Úsala cuando el consultante quiere una guía concreta y rápida: qué está pasando, qué lo traba y qué hacer.",
        "posiciones": [
            {"id": 1, "nombre": "La situación", "descripcion": "Lo que está ocurriendo realmente", "x": 22, "y": 50},
            {"id": 2, "nombre": "El obstáculo", "descripcion": "Lo que estorba o complica", "x": 50, "y": 50},
            {"id": 3, "nombre": "El consejo", "descripcion": "La acción o actitud recomendada", "x": 78, "y": 50},
        ],
        "fuente": "Tarot clásico", "enfoque": "practico",
    },
    "raiz_problema": {
        "nombre": "Raíz del Problema (4 cartas)",
        "num_cartas": 4,
        "descripcion": "Úsala cuando hay un síntoma o conflicto repetido y quieres bajar hasta su causa profunda y la salida.",
        "posiciones": [
            {"id": 1, "nombre": "El síntoma", "descripcion": "Cómo se manifiesta el problema hoy", "x": 50, "y": 14},
            {"id": 2, "nombre": "La causa profunda", "descripcion": "La raíz real, a menudo oculta", "x": 50, "y": 40},
            {"id": 3, "nombre": "La lección", "descripcion": "Lo que la situación viene a enseñar", "x": 50, "y": 64},
            {"id": 4, "nombre": "La salida", "descripcion": "El camino para resolver desde la raíz", "x": 50, "y": 88},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "zodiacal": {
        "nombre": "Rueda Zodiacal (12 cartas)",
        "num_cartas": 12,
        "descripcion": "Úsala para una panorámica de vida: una carta por cada casa astrológica (yo, dinero, comunicación, hogar, amor, trabajo, pareja, transformación, creencias, vocación, amistades, inconsciente).",
        "posiciones": [
            {"id": 1,  "nombre": "Casa I — Yo", "descripcion": "Identidad y cómo te muestras", "x": 50, "y": 12},
            {"id": 2,  "nombre": "Casa II — Recursos", "descripcion": "Dinero, valores, autoestima", "x": 69, "y": 17},
            {"id": 3,  "nombre": "Casa III — Mente", "descripcion": "Comunicación, aprendizaje, hermanos", "x": 83, "y": 31},
            {"id": 4,  "nombre": "Casa IV — Hogar", "descripcion": "Familia, raíces, lo íntimo", "x": 88, "y": 50},
            {"id": 5,  "nombre": "Casa V — Creatividad", "descripcion": "Romance, hijos, expresión, juego", "x": 83, "y": 69},
            {"id": 6,  "nombre": "Casa VI — Trabajo y salud", "descripcion": "Rutina, servicio, cuerpo", "x": 69, "y": 83},
            {"id": 7,  "nombre": "Casa VII — Pareja", "descripcion": "Relaciones uno a uno, socios", "x": 50, "y": 88},
            {"id": 8,  "nombre": "Casa VIII — Transformación", "descripcion": "Crisis, sexualidad, lo compartido", "x": 31, "y": 83},
            {"id": 9,  "nombre": "Casa IX — Sentido", "descripcion": "Creencias, viajes, filosofía", "x": 17, "y": 69},
            {"id": 10, "nombre": "Casa X — Vocación", "descripcion": "Profesión, propósito público", "x": 12, "y": 50},
            {"id": 11, "nombre": "Casa XI — Comunidad", "descripcion": "Amistades, proyectos, futuro", "x": 17, "y": 31},
            {"id": 12, "nombre": "Casa XII — Inconsciente", "descripcion": "Lo oculto, espiritualidad, cierre", "x": 31, "y": 17},
        ],
        "fuente": "Tarot astrológico", "enfoque": "vital",
    },
    "estrella": {
        "nombre": "La Estrella (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para reconectar con la esperanza y los dones: lo que te ilumina, tus recursos y hacia qué luz caminar.",
        "posiciones": [
            {"id": 1, "nombre": "La luz / la meta", "descripcion": "Lo que te orienta y da esperanza", "x": 50, "y": 14},
            {"id": 2, "nombre": "Tu don", "descripcion": "El recurso que ya tienes", "x": 84, "y": 39},
            {"id": 3, "nombre": "El reto", "descripcion": "Lo que debes atravesar", "x": 71, "y": 79},
            {"id": 4, "nombre": "El apoyo", "descripcion": "Lo que o quién te sostiene", "x": 29, "y": 79},
            {"id": 5, "nombre": "El primer paso", "descripcion": "Cómo empezar a moverte hacia la luz", "x": 16, "y": 39},
        ],
        "fuente": "Tarot espiritual", "enfoque": "espiritual",
    },
    "piramide": {
        "nombre": "La Pirámide (6 cartas)",
        "num_cartas": 6,
        "descripcion": "Úsala para construir un objetivo paso a paso: desde las bases hasta la cima de lo que quieres lograr.",
        "posiciones": [
            {"id": 1, "nombre": "La cima / la meta", "descripcion": "Lo que se quiere alcanzar", "x": 50, "y": 18},
            {"id": 2, "nombre": "Pilar interno", "descripcion": "Lo que aportas tú", "x": 37, "y": 47},
            {"id": 3, "nombre": "Pilar externo", "descripcion": "Lo que aporta el entorno", "x": 63, "y": 47},
            {"id": 4, "nombre": "Base 1 — recurso", "descripcion": "Una fortaleza con la que cuentas", "x": 25, "y": 80},
            {"id": 5, "nombre": "Base 2 — acción", "descripcion": "El esfuerzo concreto requerido", "x": 50, "y": 80},
            {"id": 6, "nombre": "Base 3 — tiempo", "descripcion": "El ritmo o plazo realista", "x": 75, "y": 80},
        ],
        "fuente": "Tarot clásico", "enfoque": "practico",
    },
    "arbol_genealogico": {
        "nombre": "Árbol Transgeneracional (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Úsala para leer el sistema familiar: qué heredaste de padres y abuelos, qué lealtades cargas y qué pide ser sanado. Puente directo con constelaciones y biodescodificación.",
        "posiciones": [
            {"id": 1, "nombre": "El consultante", "descripcion": "Tú en el árbol familiar", "x": 50, "y": 82},
            {"id": 2, "nombre": "La madre", "descripcion": "Herencia y vínculo materno", "x": 35, "y": 52},
            {"id": 3, "nombre": "El padre", "descripcion": "Herencia y vínculo paterno", "x": 65, "y": 52},
            {"id": 4, "nombre": "Abuela materna", "descripcion": "Lo que viene por la línea materna femenina", "x": 18, "y": 22},
            {"id": 5, "nombre": "Abuelo materno", "descripcion": "Lo que viene por la línea materna masculina", "x": 40, "y": 22},
            {"id": 6, "nombre": "Abuela paterna", "descripcion": "Lo que viene por la línea paterna femenina", "x": 60, "y": 22},
            {"id": 7, "nombre": "Abuelo paterno", "descripcion": "Lo que viene por la línea paterna masculina", "x": 82, "y": 22},
        ],
        "fuente": "Tarot transgeneracional", "enfoque": "transgeneracional",
    },
    "herida_sanacion": {
        "nombre": "La Herida y su Sanación (6 cartas)",
        "num_cartas": 6,
        "descripcion": "Úsala en trabajo terapéutico de una herida emocional: de dónde nace, cómo opera hoy y qué recurso la sana.",
        "posiciones": [
            {"id": 1, "nombre": "La herida", "descripcion": "El dolor central a trabajar", "x": 30, "y": 22},
            {"id": 2, "nombre": "El origen", "descripcion": "Dónde y cuándo se formó", "x": 30, "y": 50},
            {"id": 3, "nombre": "Cómo se manifiesta hoy", "descripcion": "El patrón actual que genera", "x": 30, "y": 78},
            {"id": 4, "nombre": "El recurso interno", "descripcion": "La fuerza propia para sanar", "x": 70, "y": 22},
            {"id": 5, "nombre": "El aprendizaje", "descripcion": "El sentido o regalo de la herida", "x": 70, "y": 50},
            {"id": 6, "nombre": "La sanación", "descripcion": "El paso que integra y libera", "x": 70, "y": 78},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "nino_interior": {
        "nombre": "El Niño Interior (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para contactar con el niño interior: cómo está hoy, qué le faltó, qué pide ahora y cómo nutrirlo.",
        "posiciones": [
            {"id": 1, "nombre": "El niño hoy", "descripcion": "Cómo se siente esa parte interna", "x": 50, "y": 50},
            {"id": 2, "nombre": "Su herida", "descripcion": "Lo que le dolió o faltó", "x": 50, "y": 18},
            {"id": 3, "nombre": "Lo que necesitó", "descripcion": "Lo que no recibió entonces", "x": 20, "y": 50},
            {"id": 4, "nombre": "Lo que pide ahora", "descripcion": "Su necesidad presente", "x": 80, "y": 50},
            {"id": 5, "nombre": "Cómo nutrirlo", "descripcion": "El acto concreto de cuidado", "x": 50, "y": 82},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "lazo_familiar": {
        "nombre": "Lazo con un Familiar (4 cartas)",
        "num_cartas": 4,
        "descripcion": "Úsala para entender y sanar el vínculo con una persona concreta de la familia: qué los une y qué cura el lazo.",
        "posiciones": [
            {"id": 1, "nombre": "Tú", "descripcion": "Tu posición en el vínculo", "x": 28, "y": 30},
            {"id": 2, "nombre": "El familiar", "descripcion": "La posición de la otra persona", "x": 72, "y": 30},
            {"id": 3, "nombre": "Lo que los une", "descripcion": "El lazo, lo pendiente entre ambos", "x": 50, "y": 56},
            {"id": 4, "nombre": "Lo que sana el lazo", "descripcion": "Lo que permite reconciliar o soltar", "x": 50, "y": 84},
        ],
        "fuente": "Tarot transgeneracional", "enfoque": "transgeneracional",
    },
    "profesion": {
        "nombre": "Camino Profesional (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para orientar trabajo o vocación: dónde estás, tus dones, el obstáculo, la oportunidad y el siguiente paso.",
        "posiciones": [
            {"id": 1, "nombre": "Dónde estás", "descripcion": "Tu situación laboral actual", "x": 20, "y": 75},
            {"id": 2, "nombre": "Tus dones", "descripcion": "Tus talentos y recursos", "x": 35, "y": 45},
            {"id": 3, "nombre": "El obstáculo", "descripcion": "Lo que frena tu avance", "x": 50, "y": 28},
            {"id": 4, "nombre": "La oportunidad", "descripcion": "La puerta que se abre", "x": 65, "y": 45},
            {"id": 5, "nombre": "El siguiente paso", "descripcion": "La acción que conviene tomar", "x": 80, "y": 75},
        ],
        "fuente": "Tarot clásico", "enfoque": "profesional",
    },
    "abundancia": {
        "nombre": "Abundancia y Dinero (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para trabajar la relación con el dinero: el bloqueo, la creencia heredada y cómo abrir el flujo.",
        "posiciones": [
            {"id": 1, "nombre": "Tu relación con el dinero", "descripcion": "Cómo vives la abundancia hoy", "x": 50, "y": 50},
            {"id": 2, "nombre": "El bloqueo", "descripcion": "Lo que limita el flujo", "x": 50, "y": 18},
            {"id": 3, "nombre": "La creencia heredada", "descripcion": "El mandato familiar sobre el dinero", "x": 50, "y": 82},
            {"id": 4, "nombre": "Tu recurso", "descripcion": "La fortaleza para prosperar", "x": 20, "y": 50},
            {"id": 5, "nombre": "Acción para abrir flujo", "descripcion": "El paso concreto hacia la abundancia", "x": 80, "y": 50},
        ],
        "fuente": "Tarot clásico", "enfoque": "practico",
    },
    "salud_integral": {
        "nombre": "Salud Integral (6 cartas)",
        "num_cartas": 6,
        "descripcion": "Úsala para leer un proceso de salud de forma holística: cuerpo, energía, la emoción asociada y el mensaje del síntoma.",
        "posiciones": [
            {"id": 1, "nombre": "El cuerpo físico", "descripcion": "El estado físico actual", "x": 30, "y": 22},
            {"id": 2, "nombre": "La energía vital", "descripcion": "El nivel y flujo de vitalidad", "x": 50, "y": 22},
            {"id": 3, "nombre": "La emoción asociada", "descripcion": "El sentir detrás del síntoma", "x": 70, "y": 22},
            {"id": 4, "nombre": "El mensaje del síntoma", "descripcion": "Lo que el cuerpo intenta decir", "x": 30, "y": 75},
            {"id": 5, "nombre": "Lo que pide atención", "descripcion": "Aquello a atender primero", "x": 50, "y": 75},
            {"id": 6, "nombre": "Camino de equilibrio", "descripcion": "Cómo recuperar la armonía", "x": 70, "y": 75},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "tres_caminos": {
        "nombre": "Tres Caminos (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Úsala cuando hay tres opciones sobre la mesa: la situación y, por cada camino, su naturaleza y su resultado probable.",
        "posiciones": [
            {"id": 1, "nombre": "La situación", "descripcion": "El punto de partida común", "x": 50, "y": 13},
            {"id": 2, "nombre": "Camino A", "descripcion": "La naturaleza de la opción A", "x": 20, "y": 46},
            {"id": 3, "nombre": "Resultado A", "descripcion": "Adónde lleva A", "x": 20, "y": 80},
            {"id": 4, "nombre": "Camino B", "descripcion": "La naturaleza de la opción B", "x": 50, "y": 46},
            {"id": 5, "nombre": "Resultado B", "descripcion": "Adónde lleva B", "x": 50, "y": 80},
            {"id": 6, "nombre": "Camino C", "descripcion": "La naturaleza de la opción C", "x": 80, "y": 46},
            {"id": 7, "nombre": "Resultado C", "descripcion": "Adónde lleva C", "x": 80, "y": 80},
        ],
        "fuente": "Tarot clásico", "enfoque": "decision",
    },
    "mensaje_guias": {
        "nombre": "Mensaje de los Guías (3 cartas)",
        "num_cartas": 3,
        "descripcion": "Úsala para una guía espiritual breve: lo que necesitas saber, lo que conviene soltar y lo que te sostiene.",
        "posiciones": [
            {"id": 1, "nombre": "Lo que necesitas saber", "descripcion": "El mensaje principal del momento", "x": 22, "y": 50},
            {"id": 2, "nombre": "Lo que debes soltar", "descripcion": "Aquello que ya no te sirve", "x": 50, "y": 50},
            {"id": 3, "nombre": "Lo que te sostiene", "descripcion": "El apoyo invisible con el que cuentas", "x": 78, "y": 50},
        ],
        "fuente": "Tarot espiritual", "enfoque": "espiritual",
    },
    "karma_vidas": {
        "nombre": "Karma y Patrones (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para un patrón que se repite a lo largo de la vida: su origen, lo aprendido, lo pendiente y la liberación.",
        "posiciones": [
            {"id": 1, "nombre": "El patrón", "descripcion": "Lo que se repite una y otra vez", "x": 50, "y": 14},
            {"id": 2, "nombre": "El origen", "descripcion": "De dónde nace el patrón", "x": 50, "y": 32},
            {"id": 3, "nombre": "Lo aprendido", "descripcion": "Lo que ya integraste", "x": 50, "y": 50},
            {"id": 4, "nombre": "Lo pendiente", "descripcion": "La lección aún abierta", "x": 50, "y": 68},
            {"id": 5, "nombre": "La liberación", "descripcion": "Cómo cerrar el ciclo", "x": 50, "y": 86},
        ],
        "fuente": "Tarot espiritual", "enfoque": "espiritual",
    },
    "tres_niveles": {
        "nombre": "Los Tres Niveles (3 cartas)",
        "num_cartas": 3,
        "descripcion": "Úsala para ver qué pasa dentro: lo consciente, lo subconsciente y lo superconsciente frente a un tema.",
        "posiciones": [
            {"id": 1, "nombre": "Consciente", "descripcion": "Lo que sabes y reconoces", "x": 50, "y": 18},
            {"id": 2, "nombre": "Subconsciente", "descripcion": "Lo que opera sin que lo veas", "x": 50, "y": 50},
            {"id": 3, "nombre": "Superconsciente", "descripcion": "La guía superior o el sentido mayor", "x": 50, "y": 82},
        ],
        "fuente": "Tarot psicológico", "enfoque": "terapeutico",
    },
    "cuatro_elementos": {
        "nombre": "Los Cuatro Elementos (4 cartas)",
        "num_cartas": 4,
        "descripcion": "Úsala para un chequeo de tus cuatro planos: acción (fuego), emoción (agua), mente (aire) y cuerpo/material (tierra).",
        "posiciones": [
            {"id": 1, "nombre": "Fuego — acción", "descripcion": "Tu energía, voluntad y proyectos", "x": 50, "y": 16},
            {"id": 2, "nombre": "Agua — emoción", "descripcion": "Tu mundo afectivo y vínculos", "x": 82, "y": 50},
            {"id": 3, "nombre": "Tierra — cuerpo", "descripcion": "Tu plano material, cuerpo y recursos", "x": 50, "y": 84},
            {"id": 4, "nombre": "Aire — mente", "descripcion": "Tus pensamientos y comunicación", "x": 18, "y": 50},
        ],
        "fuente": "Tarot clásico", "enfoque": "vital",
    },
    "cierre_ciclo": {
        "nombre": "Cierre de un Ciclo (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala ante una ruptura o final: lo que termina, por qué, lo aprendido, lo que se suelta y lo que se abre.",
        "posiciones": [
            {"id": 1, "nombre": "Lo que termina", "descripcion": "El ciclo que se cierra", "x": 12, "y": 50},
            {"id": 2, "nombre": "Por qué", "descripcion": "El sentido del cierre", "x": 31, "y": 50},
            {"id": 3, "nombre": "Lo aprendido", "descripcion": "El regalo de esta etapa", "x": 50, "y": 50},
            {"id": 4, "nombre": "Lo que sueltas", "descripcion": "Lo que conviene dejar ir", "x": 69, "y": 50},
            {"id": 5, "nombre": "Lo que se abre", "descripcion": "El nuevo comienzo posible", "x": 88, "y": 50},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "nueva_relacion": {
        "nombre": "¿Avanzo con esta relación? (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala cuando dudas si seguir con un vínculo nuevo: cómo es de verdad, qué ofrece, qué cuesta, tu miedo y el consejo.",
        "posiciones": [
            {"id": 1, "nombre": "Cómo es realmente", "descripcion": "La verdad del vínculo más allá de la ilusión", "x": 50, "y": 50},
            {"id": 2, "nombre": "Lo que te ofrece", "descripcion": "El potencial y lo bueno", "x": 50, "y": 18},
            {"id": 3, "nombre": "Lo que te cuesta", "descripcion": "El precio o el reto", "x": 50, "y": 82},
            {"id": 4, "nombre": "Tu miedo", "descripcion": "Lo que proyectas o temes", "x": 20, "y": 50},
            {"id": 5, "nombre": "El consejo", "descripcion": "Qué conviene hacer", "x": 80, "y": 50},
        ],
        "fuente": "Tarot relacional", "enfoque": "relacional",
    },
    "espejo_alma": {
        "nombre": "Espejo del Alma (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala para autoconocimiento: quién crees ser, quién eres de verdad, tu máscara, tu don y tu próxima evolución.",
        "posiciones": [
            {"id": 1, "nombre": "Quién eres realmente", "descripcion": "Tu esencia", "x": 50, "y": 50},
            {"id": 2, "nombre": "Quién crees ser", "descripcion": "Tu autoimagen", "x": 28, "y": 28},
            {"id": 3, "nombre": "Tu máscara", "descripcion": "Lo que muestras a los demás", "x": 72, "y": 28},
            {"id": 4, "nombre": "Tu don", "descripcion": "El talento por desarrollar", "x": 28, "y": 72},
            {"id": 5, "nombre": "Tu evolución", "descripcion": "Tu siguiente paso de crecimiento", "x": 72, "y": 72},
        ],
        "fuente": "Tarot psicológico", "enfoque": "terapeutico",
    },
    "proyecto": {
        "nombre": "Nuevo Proyecto (6 cartas)",
        "num_cartas": 6,
        "descripcion": "Úsala para evaluar un emprendimiento o idea: su fortaleza, su debilidad, lo que ayuda, lo que estorba y el resultado probable.",
        "posiciones": [
            {"id": 1, "nombre": "La idea", "descripcion": "El corazón del proyecto", "x": 30, "y": 22},
            {"id": 2, "nombre": "Fortaleza", "descripcion": "Lo que lo hace fuerte", "x": 50, "y": 22},
            {"id": 3, "nombre": "Debilidad", "descripcion": "Su punto frágil", "x": 70, "y": 22},
            {"id": 4, "nombre": "Lo que ayuda", "descripcion": "Apoyos y oportunidades", "x": 30, "y": 75},
            {"id": 5, "nombre": "Lo que estorba", "descripcion": "Obstáculos y riesgos", "x": 50, "y": 75},
            {"id": 6, "nombre": "Resultado probable", "descripcion": "Hacia dónde tiende", "x": 70, "y": 75},
        ],
        "fuente": "Tarot clásico", "enfoque": "profesional",
    },
    "diamante": {
        "nombre": "El Diamante (4 cartas)",
        "num_cartas": 4,
        "descripcion": "Úsala para una lectura rápida y clara de cualquier tema: la situación, lo oculto, el consejo y el resultado.",
        "posiciones": [
            {"id": 1, "nombre": "La situación", "descripcion": "Lo evidente del tema", "x": 50, "y": 16},
            {"id": 2, "nombre": "Lo oculto", "descripcion": "Lo que no se ve a simple vista", "x": 18, "y": 50},
            {"id": 3, "nombre": "El consejo", "descripcion": "Lo que conviene hacer", "x": 82, "y": 50},
            {"id": 4, "nombre": "El resultado", "descripcion": "El desenlace probable", "x": 50, "y": 84},
        ],
        "fuente": "Tarot clásico", "enfoque": "practico",
    },
    "semana": {
        "nombre": "La Semana (7 cartas)",
        "num_cartas": 7,
        "descripcion": "Úsala como práctica semanal: una carta para cada día, del lunes al domingo, anticipando su energía.",
        "posiciones": [
            {"id": 1, "nombre": "Lunes", "descripcion": "Energía del día", "x": 10, "y": 50},
            {"id": 2, "nombre": "Martes", "descripcion": "Energía del día", "x": 23, "y": 50},
            {"id": 3, "nombre": "Miércoles", "descripcion": "Energía del día", "x": 37, "y": 50},
            {"id": 4, "nombre": "Jueves", "descripcion": "Energía del día", "x": 50, "y": 50},
            {"id": 5, "nombre": "Viernes", "descripcion": "Energía del día", "x": 63, "y": 50},
            {"id": 6, "nombre": "Sábado", "descripcion": "Energía del día", "x": 77, "y": 50},
            {"id": 7, "nombre": "Domingo", "descripcion": "Energía del día", "x": 90, "y": 50},
        ],
        "fuente": "Tarot clásico", "enfoque": "practico",
    },
    "bloqueo": {
        "nombre": "El Bloqueo (5 cartas)",
        "num_cartas": 5,
        "descripcion": "Úsala cuando algo está estancado: qué quieres, qué lo bloquea, de dónde viene, qué soltar y cómo desbloquear.",
        "posiciones": [
            {"id": 1, "nombre": "Lo que quieres", "descripcion": "El deseo o meta", "x": 50, "y": 14},
            {"id": 2, "nombre": "Qué lo bloquea", "descripcion": "El freno actual", "x": 50, "y": 32},
            {"id": 3, "nombre": "De dónde viene", "descripcion": "El origen del bloqueo", "x": 50, "y": 50},
            {"id": 4, "nombre": "Qué soltar", "descripcion": "Lo que debes dejar ir", "x": 50, "y": 68},
            {"id": 5, "nombre": "Cómo desbloquear", "descripcion": "La acción liberadora", "x": 50, "y": 86},
        ],
        "fuente": "Tarot terapéutico", "enfoque": "terapeutico",
    },
    "mandala_personal": {
        "nombre": "Mándala Personal (9 cartas)",
        "num_cartas": 9,
        "descripcion": "Úsala para una radiografía completa en tres planos y tres tiempos: lo material, lo emocional y lo espiritual en pasado, presente y futuro.",
        "posiciones": [
            {"id": 1, "nombre": "Material — pasado", "descripcion": "Tu base material previa", "x": 25, "y": 25},
            {"id": 2, "nombre": "Material — presente", "descripcion": "Tu situación material hoy", "x": 50, "y": 25},
            {"id": 3, "nombre": "Material — futuro", "descripcion": "Hacia dónde va lo material", "x": 75, "y": 25},
            {"id": 4, "nombre": "Emocional — pasado", "descripcion": "Tu historia afectiva", "x": 25, "y": 50},
            {"id": 5, "nombre": "Emocional — presente", "descripcion": "Tu sentir actual", "x": 50, "y": 50},
            {"id": 6, "nombre": "Emocional — futuro", "descripcion": "Tu evolución emocional", "x": 75, "y": 50},
            {"id": 7, "nombre": "Espiritual — pasado", "descripcion": "Tu raíz espiritual", "x": 25, "y": 75},
            {"id": 8, "nombre": "Espiritual — presente", "descripcion": "Tu conexión hoy", "x": 50, "y": 75},
            {"id": 9, "nombre": "Espiritual — futuro", "descripcion": "Tu camino del alma", "x": 75, "y": 75},
        ],
        "fuente": "Tarot integral", "enfoque": "vital",
    },
})

# ─── Caso de uso de las tiradas base (qué pregunta responde cada una) ─────────
_USO_TIRADAS: dict[str, str] = {
    "carta_del_dia": "Úsala para empezar el día o una sesión: una sola carta marca el tema, la energía o el aviso a tener presente. Ideal como práctica diaria de consciencia.",
    "tres_cartas": "Úsala cuando quieres ver el hilo de una situación en el tiempo: de dónde viene, cómo está hoy y hacia dónde tiende. La lectura narrativa básica.",
    "cruz_simple": "Úsala cuando el consultante trae un problema concreto y quieres causa, entorno y consejo en una lectura rápida y clara.",
    "herradura": "Úsala para una situación que evoluciona y necesitas consejo práctico: pasado, presente, futuro, influencias y el camino recomendado.",
    "chakras": "Úsala para un diagnóstico energético: revela en qué centro hay bloqueo o exceso y qué pide cada chakra. Buen puente con biomagnetismo y sanación.",
    "cruz_celtica": "Úsala para un caso importante que merece análisis profundo: examina la situación desde diez ángulos (raíz, pasado, futuro, miedos, entorno y desenlace).",
    "cinco_centros": "Úsala para una radiografía completa del ser según Jodorowsky: lee pasado, presente y futuro en los cinco centros (material, sexual, emocional, creativo y espiritual).",
    "arbol_vida": "Úsala para una lectura espiritual integral según el Árbol de la Vida cabalístico: el estado del consultante en las diez sefirot, de lo material a lo divino.",
}
for _t, _d in _USO_TIRADAS.items():
    if _t in TIRADAS:
        TIRADAS[_t]["descripcion"] = _d

# ─── Correspondencias zodiacales ─────────────────────────────────────────────

# Sistema RWS: correspondencias estándar de la Golden Dawn
# Sistema Marsella: correspondencias según Jodorowsky y Camoin
SIGNO_A_MAYOR: dict[str, dict] = {
    "aries":       {"rws": 4,  "marsella": 4,  "thoth": 4},    # El Emperador
    "tauro":       {"rws": 5,  "marsella": 5,  "thoth": 5},    # Sumo Sacerdote
    "geminis":     {"rws": 6,  "marsella": 6,  "thoth": 6},    # Los Amantes
    "cancer":      {"rws": 7,  "marsella": 7,  "thoth": 7},    # El Carro
    "leo":         {"rws": 8,  "marsella": 11, "thoth": 8},    # La Fuerza
    "virgo":       {"rws": 9,  "marsella": 9,  "thoth": 9},    # El Ermitaño
    "libra":       {"rws": 11, "marsella": 8,  "thoth": 11},   # La Justicia
    "escorpio":    {"rws": 13, "marsella": 13, "thoth": 13},   # La Muerte
    "sagitario":   {"rws": 14, "marsella": 14, "thoth": 14},   # La Templanza
    "capricornio": {"rws": 15, "marsella": 15, "thoth": 15},   # El Diablo
    "acuario":     {"rws": 17, "marsella": 17, "thoth": 17},   # La Estrella
    "piscis":      {"rws": 18, "marsella": 18, "thoth": 18},   # La Luna
}

# Carta de corte (figura) por signo solar — sistema clásico
SIGNO_A_PERSONA: dict[str, str] = {
    "aries":       "Rey de Bastos",
    "tauro":       "Rey de Pentáculos",
    "geminis":     "Caballero de Espadas",
    "cancer":      "Reina de Copas",
    "leo":         "Rey de Bastos",
    "virgo":       "Reina de Pentáculos",
    "libra":       "Rey de Espadas",
    "escorpio":    "Reina de Copas",
    "sagitario":   "Caballero de Bastos",
    "capricornio": "Rey de Pentáculos",
    "acuario":     "Caballero de Espadas",
    "piscis":      "Reina de Copas",
}

# ─── Carta de lección zodiacal por fecha (decanatos) ─────────────────────────
# Basado en las correspondencias clásicas de los decanatos astrológicos
# Cada decanato de 10° corresponde a un arcano menor

FECHA_A_LECCION: list[dict] = [
    # Aries
    {"inicio": (3, 21), "fin": (3, 30), "carta": "Dos de Bastos"},
    {"inicio": (3, 31), "fin": (4, 10), "carta": "Tres de Bastos"},
    {"inicio": (4, 11), "fin": (4, 20), "carta": "Cuatro de Bastos"},
    # Tauro
    {"inicio": (4, 21), "fin": (4, 30), "carta": "Cinco de Pentáculos"},
    {"inicio": (5,  1), "fin": (5, 10), "carta": "Seis de Pentáculos"},
    {"inicio": (5, 11), "fin": (5, 20), "carta": "Siete de Pentáculos"},
    # Géminis
    {"inicio": (5, 21), "fin": (5, 31), "carta": "Ocho de Espadas"},
    {"inicio": (6,  1), "fin": (6, 10), "carta": "Nueve de Espadas"},
    {"inicio": (6, 11), "fin": (6, 20), "carta": "Diez de Espadas"},
    # Cáncer
    {"inicio": (6, 21), "fin": (7,  1), "carta": "Dos de Copas"},
    {"inicio": (7,  2), "fin": (7, 11), "carta": "Tres de Copas"},
    {"inicio": (7, 12), "fin": (7, 22), "carta": "Cuatro de Copas"},
    # Leo
    {"inicio": (7, 23), "fin": (8,  1), "carta": "Cinco de Bastos"},
    {"inicio": (8,  2), "fin": (8, 11), "carta": "Seis de Bastos"},
    {"inicio": (8, 12), "fin": (8, 22), "carta": "Siete de Bastos"},
    # Virgo
    {"inicio": (8, 23), "fin": (9,  1), "carta": "Ocho de Pentáculos"},
    {"inicio": (9,  2), "fin": (9, 11), "carta": "Nueve de Pentáculos"},
    {"inicio": (9, 12), "fin": (9, 22), "carta": "Diez de Pentáculos"},
    # Libra
    {"inicio": (9, 23), "fin": (10,  2), "carta": "Dos de Espadas"},
    {"inicio": (10, 3), "fin": (10, 12), "carta": "Tres de Espadas"},
    {"inicio": (10, 13),"fin": (10, 22), "carta": "Cuatro de Espadas"},
    # Escorpio
    {"inicio": (10, 23),"fin": (11, 1),  "carta": "Cinco de Copas"},
    {"inicio": (11,  2),"fin": (11, 11), "carta": "Seis de Copas"},
    {"inicio": (11, 12),"fin": (11, 21), "carta": "Siete de Copas"},
    # Sagitario
    {"inicio": (11, 22),"fin": (12, 1),  "carta": "Ocho de Bastos"},
    {"inicio": (12,  2),"fin": (12, 11), "carta": "Nueve de Bastos"},
    {"inicio": (12, 12),"fin": (12, 21), "carta": "Diez de Bastos"},
    # Capricornio
    {"inicio": (12, 22),"fin": (12, 31), "carta": "Dos de Pentáculos"},
    {"inicio": (1,   1),"fin": (1,  10), "carta": "Tres de Pentáculos"},
    {"inicio": (1,  11),"fin": (1,  19), "carta": "Cuatro de Pentáculos"},
    # Acuario
    {"inicio": (1,  20),"fin": (1,  29), "carta": "Cinco de Espadas"},
    {"inicio": (1,  30),"fin": (2,   8), "carta": "Seis de Espadas"},
    {"inicio": (2,   9),"fin": (2,  18), "carta": "Siete de Espadas"},
    # Piscis
    {"inicio": (2,  19),"fin": (2,  28), "carta": "Ocho de Copas"},
    {"inicio": (3,   1),"fin": (3,  10), "carta": "Nueve de Copas"},
    {"inicio": (3,  11),"fin": (3,  20), "carta": "Diez de Copas"},
]

# ─── Keywords numerológicos de los arcanos menores ───────────────────────────

KEYWORDS_NUMERO: dict[int, dict] = {
    1:  {"tema": "inicio", "energia": "potencial puro", "desafio": "arrancar"},
    2:  {"tema": "dualidad", "energia": "equilibrio y elección", "desafio": "decidir"},
    3:  {"tema": "crecimiento", "energia": "expansión y creatividad", "desafio": "expresión"},
    4:  {"tema": "estabilidad", "energia": "base y estructura", "desafio": "no rigidez"},
    5:  {"tema": "cambio", "energia": "conflicto y transformación", "desafio": "adaptarse"},
    6:  {"tema": "armonía", "energia": "equilibrio y cuidado", "desafio": "dar sin perder"},
    7:  {"tema": "reflexión", "energia": "introspección y evaluación", "desafio": "no aislarse"},
    8:  {"tema": "poder", "energia": "movimiento y acción", "desafio": "no precipitarse"},
    9:  {"tema": "completitud", "energia": "culminación y soltar", "desafio": "dejar ir"},
    10: {"tema": "cierre", "energia": "fin de ciclo", "desafio": "aceptar el final"},
}

# ─── Información por Palo ─────────────────────────────────────────────────────

PALO_INFO: dict[str, dict] = {
    "bastos": {
        "nombre": "Bastos",
        "elemento": "fuego",
        "chakra": "plexo solar (Manipura)",
        "funcion_jungiana": "intuición",
        "signos": ["aries", "leo", "sagitario"],
        "tema": "acción, creatividad, voluntad, inspiración, proyectos, espíritu",
        "pregunta": "¿Qué te mueve, qué te inspira, qué quieres crear?",
        "cuerpo": "energía vital, sistema nervioso simpático",
        "color_simbolico": "rojo-naranja",
    },
    "copas": {
        "nombre": "Copas",
        "elemento": "agua",
        "chakra": "corazón (Anahata)",
        "funcion_jungiana": "sentimiento",
        "signos": ["cancer", "escorpio", "piscis"],
        "tema": "emociones, amor, relaciones, intuición, inconsciente, espiritualidad",
        "pregunta": "¿Qué sientes, qué amas, cómo te relacionas?",
        "cuerpo": "sistema linfático, líquidos corporales, corazón",
        "color_simbolico": "azul-plateado",
    },
    "espadas": {
        "nombre": "Espadas",
        "elemento": "aire",
        "chakra": "garganta (Vishuddha)",
        "funcion_jungiana": "pensamiento",
        "signos": ["geminis", "libra", "acuario"],
        "tema": "mente, conflicto, verdad, comunicación, decisión, dolor y claridad",
        "pregunta": "¿Qué piensas, qué verdad percibes, qué conflictos enfrentas?",
        "cuerpo": "sistema respiratorio, sistema nervioso central",
        "color_simbolico": "amarillo-gris",
    },
    "pentaculos": {
        "nombre": "Pentáculos",
        "elemento": "tierra",
        "chakra": "raíz (Muladhara)",
        "funcion_jungiana": "sensación",
        "signos": ["tauro", "virgo", "capricornio"],
        "tema": "materia, cuerpo, dinero, trabajo, salud, natura, abundancia",
        "pregunta": "¿Qué manifiestas, qué construyes, qué vale materialmente?",
        "cuerpo": "sistema óseo, piel, sistema digestivo",
        "color_simbolico": "verde-dorado",
    },
}
